[packages.armazem-siafi-2024]

path = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2024/main/datapackage.json"
resources = ["receita", "alteracoes_orcamentarias"]
token = "GITHUB_TOKEN"

[packages.armazem-siafi-2023]

path = "https://raw.githubusercontent.com/splor-mg/armazem-siafi-dados-2023/main/datapackage.json"
token = "GITHUB_TOKEN"
resources = ["receita", "alteracoes_orcamentarias"]
