# Ano anterior
[packages.armazem-siafi-2024]

path = "https://raw.githubusercontent.com/splor-mg/armazem-siafi-dados-2024/main/datapackage.json"
token = "GITHUB_TOKEN"
resources = ["receita", "alteracoes_orcamentarias"]

# Ano corrente
[packages.armazem-siafi-2025]

path = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2025/main/datapackage.json"
resources = ["receita", "alteracoes_orcamentarias"]
token = "GITHUB_TOKEN"