name: Updated

on:
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: fjuniorr/${{ github.event.repository.name }}:latest
        cache-from: type=registry,ref=fjuniorr/${{ github.event.repository.name }}:latest
        cache-to: type=inline
    - name: ETL pipeline
      env: 
        BITBUCKET_USER: ${{ secrets.BITBUCKET_USER }}
        BITBUCKET_PASSWORD: ${{ secrets.BITBUCKET_PASSWORD }}
        CKAN_HOST: ${{ secrets.CKAN_HOST }}
        CKAN_KEY: ${{ secrets.CKAN_KEY }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: docker run -e GITHUB_TOKEN=$GH_PAT -e BITBUCKET_USER=$BITBUCKET_USER -e BITBUCKET_PASSWORD=$BITBUCKET_PASSWORD -e CKAN_HOST=$CKAN_HOST -e CKAN_KEY=$CKAN_KEY --mount type=bind,source=${PWD},target=/project fjuniorr/${{ github.event.repository.name }} bash -c "Rscript -e \"remotes::install_bitbucket('dcgf/relatorios', auth_user = Sys.getenv('BITBUCKET_USER'), password = Sys.getenv('BITBUCKET_PASSWORD'))\" && make all"
    - name: Push data package
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        make push
    - name: Workflow failure notification
      uses: JasonEtco/create-an-issue@v2
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/workflow-failure.md
