name: Updated

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    # Executa de segunda a sexta-feira às 07:14 (Brasília) → 10:14 UTC
    - cron:  '14 10 * * 1-5'
  repository_dispatch:
    types: [version-updated]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Lint: garante a qualidade e padronização do código antes de executar etapas posteriores do workflow
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
    
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-ansi
    
    - name: Run Black
      run: poetry run black --check .
    
    - name: Run Flake8
      run: poetry run flake8 .
    
    - name: Run MyPy
      run: poetry run mypy .
    
    - name: Run Pytest
      run: poetry run pytest

  main:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
    
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-ansi
    
    - name: Check package versions
      continue-on-error: true
      run: poetry run pacotes-check-version
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Load config variables
      run: |
        echo "RELATORIOS_VERSION=$(grep '^RELATORIOS_VERSION=' config.mk | cut -d'=' -f2)" >> $GITHUB_ENV
        echo "EXECUCAO_VERSION=$(grep '^EXECUCAO_VERSION=' config.mk | cut -d'=' -f2)" >> $GITHUB_ENV
        echo "REEST_VERSION=$(grep '^REEST_VERSION=' config.mk | cut -d'=' -f2)" >> $GITHUB_ENV
        echo "ANO_MATRIZ=$(grep '^ANO_MATRIZ=' config.mk | cut -d'=' -f2)" >> $GITHUB_ENV
        echo "DOCKER_TAG=$(grep '^DOCKER_TAG=' config.mk | cut -d'=' -f2)" >> $GITHUB_ENV
        echo "DOCKER_USER=$(grep '^DOCKER_USER=' config.mk | cut -d'=' -f2)" >> $GITHUB_ENV
        echo "DOCKER_IMAGE=$(grep '^DOCKER_IMAGE=' config.mk | cut -d'=' -f2)" >> $GITHUB_ENV

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_USER }}/${{ github.event.repository.name }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=${{ env.DOCKER_TAG }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILDKIT: 1
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          relatorios_version=${{ env.RELATORIOS_VERSION }}
          execucao_version=${{ env.EXECUCAO_VERSION }}
          reest_version=${{ env.REEST_VERSION }}
          ano_matriz=${{ env.ANO_MATRIZ }}
          docker_tag=${{ env.DOCKER_TAG }}
          docker_user=${{ env.DOCKER_USER }}
          docker_image=${{ env.DOCKER_IMAGE }}
        secrets: |
          secret=${{ secrets.GH_PAT }}
        cache-from: type=registry,ref=${{ env.DOCKER_USER }}/${{ github.event.repository.name }}:latest
        cache-to: type=registry,ref=${{ env.DOCKER_USER }}/${{ github.event.repository.name }}:latest,mode=max
    - name: ETL pipeline
      env: 
        CKAN_HOST: ${{ secrets.CKAN_HOST }}
        CKAN_KEY: ${{ secrets.CKAN_KEY }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        # Executar todo o pipeline dentro do Docker para garantir consistência
        docker run -e GITHUB_TOKEN=$GH_PAT -e CKAN_HOST=$CKAN_HOST -e CKAN_KEY=$CKAN_KEY \
          --mount type=bind,source=${PWD},target=/project \
          aidsplormg/${{ github.event.repository.name }}:${{ env.DOCKER_TAG }} \
          bash -c "make all"
    - name: Push data package
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        make push
    - name: Workflow failure notification
      uses: JasonEtco/create-an-issue@v2
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/workflow-failure.md

  # Validação: verifica integridade e qualidade dos dados gerados
  validate-data:
    needs: main
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
    
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-ansi
    
    - name: Validate with Frictionless
      run: poetry run frictionless validate datapackage.yaml
    
    - name: Check generated files exist
      run: |
        echo "🔍 Verificando se todos os arquivos foram gerados..."
        required_files=(
          "data/matriz_receita.csv"
          "data/matriz_despesa.csv"
          "data/fonte_stn.csv"
          "data/matriz_receita_desc.xlsx"
          "data/matriz_despesa_desc.xlsx"
        )
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "❌ Arquivo obrigatório não encontrado: $file"
            exit 1
          else
            echo "✅ $file existe"
          fi
        done
        echo "✅ Todos os arquivos obrigatórios foram gerados"
    
    - name: Validate CSV structure
      run: |
        echo "🔍 Validando estrutura dos arquivos CSV..."
        
        # Verificar se CSVs têm cabeçalho e dados
        for csv in data/matriz_receita.csv data/matriz_despesa.csv data/fonte_stn.csv; do
          echo "Validando $csv..."
          if [ ! -s "$csv" ]; then
            echo "❌ $csv está vazio"
            exit 1
          fi
          
          # Verificar se tem pelo menos 2 linhas (cabeçalho + dados)
          line_count=$(wc -l < "$csv")
          if [ "$line_count" -lt 2 ]; then
            echo "❌ $csv tem apenas $line_count linha(s), esperado pelo menos 2"
            exit 1
          fi
          
          echo "✅ $csv tem $line_count linhas"
        done
    
    - name: Validate XLSX files
      run: |
        echo "🔍 Validando arquivos XLSX..."
        
        # Verificar se XLSX existem e não estão vazios
        for xlsx in data/matriz_receita_desc.xlsx data/matriz_despesa_desc.xlsx; do
          if [ ! -f "$xlsx" ] || [ ! -s "$xlsx" ]; then
            echo "❌ $xlsx não existe ou está vazio"
            exit 1
          fi
          echo "✅ $xlsx existe e não está vazio"
        done
    
    - name: Validate data consistency
      run: |
        echo "🔍 Validando consistência dos dados..."
        
        # Verificar se matriz_receita e matriz_despesa têm colunas similares
        receita_cols=$(head -1 data/matriz_receita.csv | tr ',' '\n' | wc -l)
        despesa_cols=$(head -1 data/matriz_despesa.csv | tr ',' '\n' | wc -l)
        
        echo "Matriz receita: $receita_cols colunas"
        echo "Matriz despesa: $despesa_cols colunas"
        
        if [ "$receita_cols" -lt 3 ] || [ "$despesa_cols" -lt 3 ]; then
          echo "❌ Arquivos CSV têm muito poucas colunas"
          exit 1
        fi
        
        echo "✅ Estrutura dos dados parece consistente"
    
    - name: Data validation summary
      run: |
        echo "🎉 Validação de dados concluída com sucesso!"
        echo "📊 Arquivos validados:"
        ls -la data/*.csv data/*.xlsx
        echo ""
        echo "📈 Estatísticas:"
        for file in data/*.csv; do
          lines=$(wc -l < "$file")
          echo "  $(basename "$file"): $lines linhas"
        done

  # Limpeza: otimiza recursos e limpa arquivos temporários
  cleanup:
    needs: validate-data
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Clean temporary files
      run: |
        echo "🧹 Limpando arquivos temporários..."
        
        # Limpar cache do Poetry se existir
        if [ -d ".venv" ]; then
          echo "Removendo cache do Poetry..."
          rm -rf .venv
        fi
        
        # Limpar arquivos temporários do sistema
        echo "Limpando cache do sistema..."
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        
        # Limpar logs antigos
        echo "Limpando logs antigos..."
        find . -name "*.log" -type f -mtime +1 -delete 2>/dev/null || true
        
        echo "✅ Limpeza concluída"
    
    - name: Optimize workspace
      run: |
        echo "⚡ Otimizando workspace..."
        
        # Verificar uso de disco
        echo "📊 Uso de disco atual:"
        df -h
        
        # Limpar arquivos desnecessários
        echo "Removendo arquivos desnecessários..."
        find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
        find . -name "*.pyc" -type f -delete 2>/dev/null || true
        find . -name ".pytest_cache" -type d -exec rm -rf {} + 2>/dev/null || true
        
        echo "✅ Workspace otimizado"
    
    - name: Generate cleanup report
      run: |
        echo "📋 Relatório de limpeza:"
        echo "  - Cache do Poetry: removido"
        echo "  - Arquivos temporários: limpos"
        echo "  - Cache do sistema: otimizado"
        echo "  - Arquivos Python compilados: removidos"
        echo "  - Workspace: otimizado"

  # Resumo: relatório final consolidado da execução
  summary:
    needs: [lint, main, validate-data, cleanup]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Generate execution summary
      run: |
        echo "🎯 RESUMO FINAL DA EXECUÇÃO"
        echo "================================"
        echo ""
        echo "📅 Data/Hora: $(date '+%Y-%m-%d %H:%M:%S')"
        echo "🌿 Branch: ${{ github.ref_name }}"
        echo "📝 Commit: ${{ github.sha }}"
        echo "👤 Ator: ${{ github.actor }}"
        echo ""
        echo "📊 Status dos Jobs:"
        echo "  - Lint: ${{ needs.lint.result }}"
        echo "  - Main: ${{ needs.main.result }}"
        echo "  - Validate Data: ${{ needs.validate-data.result }}"
        echo "  - Cleanup: ${{ needs.cleanup.result }}"
        echo ""
        echo "🔗 Links Úteis:"
        echo "  - Workflow Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        echo "  - Commit: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
        echo "  - Branch: ${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}"
        echo ""
        echo "📈 Estatísticas dos Dados:"
        if [ -d "data" ]; then
          for file in data/*.csv data/*.xlsx 2>/dev/null; do
            if [ -f "$file" ]; then
              size=$(du -h "$file" | cut -f1)
              if [[ "$file" == *.csv ]]; then
                lines=$(wc -l < "$file" 2>/dev/null || echo "N/A")
                echo "  - $(basename "$file"): $size ($lines linhas)"
              else
                echo "  - $(basename "$file"): $size"
              fi
            fi
          done
        else
          echo "  - Diretório data não encontrado"
        fi
        echo ""
        echo "✅ Execução finalizada com sucesso!"
        echo "================================"
